# ao-dev-cli options
stack_size: 3145728 # 3MiB
initial_memory: 4194304 # 4MiB stack size is included in initial memory, along with heap
maximum_memory: 1073741824 # 1GiB
target: 32 # wasm32 or wasm 64
# extra info
aos_git_hash: 'e9fc10c54b4f21302ee8d084d31f3383b46857b2' # used to pull in the 'process' folder at a specific git hash
compute_limit: '9000000000000' # used in publishing
module_format: 'wasm32-unknown-emscripten-metering'
